version: '3'

services:
  db:
    container_name: GameDB
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: pw
      MYSQL_DATABASE: GameDB
      MYSQL_USER: GameDBUser
      MYSQL_PASSWORD: pw
    ports:
      - "9906:3306"
  web:
    container_name: GameApp
    image: php:7.2.2-apache
    depends_on:
      - db
    volumes:
      - ./php/:/var/www/html/
    ports:
      - "8100:80"
    stdin_open: true
    tty: true
